export function createConversationControllers({
  agentCatalog,
  agentSkills,
  app,
  attachments,
  composerContext,
  conversationActions,
  knowledgeBase,
  messageActions,
  timeline,
}) {
  const timelineController = {
    activeGroup: app.activeGroup,
    activeRun: app.activeRun,
    activeRunHasAgentRuns: timeline.activeRunHasAgentRuns,
    activeRunProgress: timeline.activeRunProgress,
    activeTurnRailId: timeline.activeTurnRailId,
    attachmentKind: attachments.attachmentKind,
    attachmentMediaUrl: attachments.attachmentMediaUrl,
    attachmentPreviewUrl: attachments.attachmentPreviewUrl,
    attachmentTypeLabel: attachments.attachmentTypeLabel,
    conversationEmptyVisible: timeline.conversationEmptyVisible,
    copyMessageContent: messageActions.copyMessageContent,
    deletingMessageId: messageActions.deletingMessageId,
    directConclusionLiveStatus: timeline.directConclusionLiveStatus,
    directTraceEventLiveStatus: timeline.directTraceEventLiveStatus,
    dismissSystemMessage: timeline.dismissSystemMessage,
    displayedRun: timeline.displayedRun,
    displayedRunAgentForKind: timeline.displayedRunAgentForKind,
    displayedRunAgentKind: timeline.displayedRunAgentKind,
    displayedRunAgentRuns: timeline.displayedRunAgentRuns,
    displayedRunAgentStatus: timeline.displayedRunAgentStatus,
    displayedRunAgentStatusForKind: timeline.displayedRunAgentStatusForKind,
    displayedRunAgentTone: timeline.displayedRunAgentTone,
    displayedRunAgentToneForKind: timeline.displayedRunAgentToneForKind,
    displayedRunAgentTraceLabel: timeline.displayedRunAgentTraceLabel,
    displayedRunLabel: timeline.displayedRunLabel,
    displayedRunTargetKinds: timeline.displayedRunTargetKinds,
    displayedRunTopicRootId: timeline.displayedRunTopicRootId,
    emptyShowcaseIndex: app.emptyShowcaseIndex,
    focusTurn: timeline.focusTurn,
    formatTime: timeline.formatTime,
    formatAttachmentSize: attachments.formatAttachmentSize,
    handleMessageScroll: app.handleMessageScroll,
    isActiveRunTopic: timeline.isActiveRunTopic,
    isDirectTraceOpen: timeline.isDirectTraceOpen,
    isDismissibleSystemWarning: timeline.isDismissibleSystemWarning,
    isDisplayedCoordinatedRun: timeline.isDisplayedCoordinatedRun,
    isImageAttachment: attachments.isImageAttachment,
    isMessageCopied: messageActions.isMessageCopied,
    isTopicExpanded: timeline.isTopicExpanded,
    isTopicRoot: timeline.isTopicRoot,
    knowledgeBaseLogo: knowledgeBase.knowledgeBaseLogo,
    knowledgeBaseName: knowledgeBase.knowledgeBaseName,
    localizedStepTitle: timeline.localizedStepTitle,
    messageAgentRunId: timeline.messageAgentRunId,
    messageAttachments: attachments.messageAttachments,
    messageDeleteArmedId: messageActions.messageDeleteArmedId,
    messageDeleteDisabled: messageActions.messageDeleteDisabled,
    messageDeleteTitle: messageActions.messageDeleteTitle,
    messageElapsedLabel: timeline.messageElapsedLabel,
    messageElementId: timeline.messageElementId,
    messageExecutionSteps: timeline.messageExecutionSteps,
    messageHasTrace: timeline.messageHasTrace,
    messageScroller: app.messageScroller,
    messageThreadRootId: timeline.messageThreadRootId,
    messageTraceEvents: timeline.messageTraceEvents,
    messageTraceKey: timeline.messageTraceKey,
    messageTraceStatus: timeline.messageTraceStatus,
    messageTraceSummary: timeline.messageTraceSummary,
    openDisplayedRunTrace: timeline.openDisplayedRunTrace,
    openAttachment: attachments.openAttachment,
    openDisplayedTraceForAgent: timeline.openDisplayedTraceForAgent,
    openTraceForMessage: timeline.openTraceForMessage,
    productWordmark: app.productWordmark,
    provisionalMessages: timeline.provisionalMessages,
    requestMessageDelete: messageActions.requestMessageDelete,
    runRoundProgress: timeline.runRoundProgress,
    runStatusLabel: timeline.runStatusLabel,
    runStatusTone: timeline.runStatusTone,
    syncDirectTraceDisclosure: timeline.syncDirectTraceDisclosure,
    t: app.t,
    terminalSystemConclusion: timeline.terminalSystemConclusion,
    theme: app.theme,
    timelineMessages: timeline.timelineMessages,
    toggleTopic: timeline.toggleTopic,
    topicReplyAgentKinds: timeline.topicReplyAgentKinds,
    topicReplyCount: timeline.topicReplyCount,
    topicReplyLabel: timeline.topicReplyLabel,
    topicToggleLabel: timeline.topicToggleLabel,
    traceEventTitle: timeline.traceEventTitle,
    traceEventTypeLabel: timeline.traceEventTypeLabel,
    translateSystemMessage: app.translateSystemMessage,
    turnRailItems: timeline.turnRailItems,
    turnRailLabel: timeline.turnRailLabel,
    vAttachmentPreview: attachments.vAttachmentPreview,
  }

  const conversationHeaderController = {
    activeDirectAgent: agentCatalog.activeDirectAgent,
    activeGroup: app.activeGroup,
    activeRun: app.activeRun,
    agentImageLabel: agentCatalog.agentImageLabel,
    agentSkillLabel: agentSkills.agentSkillLabel,
    beginInlineTitleEdit: conversationActions.beginInlineTitleEdit,
    cancelInlineTitleEdit: conversationActions.cancelInlineTitleEdit,
    compactPath: app.compactPath,
    conversationPermissionLabel: app.conversationPermissionLabel,
    groupName: app.groupName,
    inlineTitleDraft: conversationActions.inlineTitleDraft,
    inlineTitleEditing: conversationActions.inlineTitleEditing,
    openGroupSettings: conversationActions.openGroupSettings,
    providerModeShortLabel: agentCatalog.providerModeShortLabel,
    saveInlineTitle: conversationActions.saveInlineTitle,
    saving: app.saving,
    sending: app.sending,
    shortcutDefinitions: app.shortcutDefinitions,
    shortcutMenuOpen: app.shortcutMenuOpen,
    t: app.t,
    theme: app.theme,
  }

  const composerController = {
    activeGroup: app.activeGroup,
    activeRun: app.activeRun,
    activeSkillOptionId: composerContext.activeSkillOptionId,
    attachmentActionLabel: attachments.attachmentActionLabel,
    attachmentKind: attachments.attachmentKind,
    canSendMessage: app.canSendMessage,
    composerAttachmentSupported: attachments.composerAttachmentSupported,
    composerAttachments: attachments.composerAttachments,
    composerDropActive: attachments.composerDropActive,
    composerInput: composerContext.composerInput,
    composerMenuGroups: composerContext.composerMenuGroups,
    composerMenuOptionDescription: composerContext.composerMenuOptionDescription,
    composerMenuOptionDisabled: composerContext.composerMenuOptionDisabled,
    composerMenuOptionIndex: composerContext.composerMenuOptionIndex,
    composerMenuOptionKey: composerContext.composerMenuOptionKey,
    composerMenuOptionKindLabel: composerContext.composerMenuOptionKindLabel,
    composerMenuOptionLogo: composerContext.composerMenuOptionLogo,
    composerMenuOptions: composerContext.composerMenuOptions,
    composerMenuOptionTitle: composerContext.composerMenuOptionTitle,
    discussionMode: composerContext.discussionMode,
    draft: composerContext.draft,
    groupName: app.groupName,
    handleComposerInput: composerContext.handleComposerInput,
    handleComposerKeydown: composerContext.handleComposerKeydown,
    handleComposerDragEnter: attachments.handleComposerDragEnter,
    handleComposerDragLeave: attachments.handleComposerDragLeave,
    handleComposerDragOver: attachments.handleComposerDragOver,
    handleComposerDrop: attachments.handleComposerDrop,
    handleComposerPaste: attachments.handleComposerPaste,
    importingAttachment: attachments.importingAttachment,
    isComposerTargetSelected: composerContext.isComposerTargetSelected,
    isImageAttachment: attachments.isImageAttachment,
    knowledgeBaseLogo: knowledgeBase.knowledgeBaseLogo,
    knowledgeBaseName: knowledgeBase.knowledgeBaseName,
    maxRounds: app.maxRounds,
    openSkillMenu: composerContext.openSkillMenu,
    pickAttachments: attachments.pickAttachments,
    removeAgentMention: composerContext.removeAgentMention,
    removeAttachment: attachments.removeAttachment,
    removeKnowledgeBase: composerContext.removeKnowledgeBase,
    removeSkill: composerContext.removeSkill,
    requestUnlimitedRounds: app.requestUnlimitedRounds,
    roundProgressPercent: app.roundProgressPercent,
    roundSettingsControl: app.roundSettingsControl,
    roundSettingsOpen: app.roundSettingsOpen,
    selectedAgentKinds: composerContext.selectedAgentKinds,
    selectedKnowledgeBases: composerContext.selectedKnowledgeBases,
    selectedSkills: composerContext.selectedSkills,
    selectComposerMenuOption: composerContext.selectComposerMenuOption,
    sendButtonLabel: composerContext.sendButtonLabel,
    sendMessage: app.sendMessage,
    sending: app.sending,
    skillActiveIndex: composerContext.skillActiveIndex,
    skillMenuOpen: composerContext.skillMenuOpen,
    skillsLoading: composerContext.skillsLoading,
    stopRun: app.stopRun,
    t: app.t,
    theme: app.theme,
    toggleTarget: composerContext.toggleTarget,
    unlimitedRounds: app.unlimitedRounds,
  }

  return { composerController, conversationHeaderController, timelineController }
}
