export function createWorkspaceControllers({
  agentCatalog,
  agentManagement,
  agentRefresh,
  agentSkills,
  app,
  collapsedGroupMenu,
  conversationActions,
  conversationNavigation,
  knowledgeBase,
  providerSettings,
  timeline,
}) {
  const workspaceSidebarController = {
    activeView: app.activeView,
    collapsedGroupMenu: collapsedGroupMenu.collapsedGroupMenu,
    collapsedGroupMenuButton: collapsedGroupMenu.collapsedGroupMenuButton,
    collapsedGroupMenuOpen: collapsedGroupMenu.collapsedGroupMenuOpen,
    collapsedGroupMenuStyle: collapsedGroupMenu.collapsedGroupMenuStyle,
    contentInteractionBlocked: app.contentInteractionBlocked,
    createDirectSession: conversationActions.createDirectSession,
    deleteSidebarConversation: conversationActions.deleteSidebarConversation,
    directGroupsFor: conversationNavigation.directGroupsFor,
    dismissSidebarDeleteConfirmation: conversationActions.dismissSidebarDeleteConfirmation,
    formatNavTime: conversationNavigation.formatNavTime,
    goHome: app.goHome,
    groupAgentSummary: conversationNavigation.groupAgentSummary,
    groupGroups: conversationNavigation.groupGroups,
    groupName: app.groupName,
    groupSessionListExpanded: conversationNavigation.groupSessionListExpanded,
    handleSidebarAgentMain: app.handleSidebarAgentMain,
    hasFinishedDirectRun: timeline.hasFinishedDirectRun,
    hasMoreDirectGroups: conversationNavigation.hasMoreDirectGroups,
    hasMoreGroupGroups: conversationNavigation.hasMoreGroupGroups,
    isDirectCreationPending: conversationNavigation.isDirectCreationPending,
    isDirectSessionListExpanded: conversationNavigation.isDirectSessionListExpanded,
    isGroupRunning: app.isGroupRunning,
    isSidebarAgentExpanded: conversationNavigation.isSidebarAgentExpanded,
    openConversationRename: conversationActions.openConversationRename,
    openNewGroup: conversationActions.openNewGroup,
    openSidebarConversationDelete: conversationActions.openSidebarConversationDelete,
    openSystemSettings: app.openSystemSettings,
    productMark: app.productMark,
    remainingDirectGroupsCount: conversationNavigation.remainingDirectGroupsCount,
    remainingGroupGroupsCount: conversationNavigation.remainingGroupGroupsCount,
    saving: app.saving,
    selectGroup: app.selectGroup,
    selectedGroupId: app.selectedGroupId,
    sidebarAgentSessionListId: conversationNavigation.sidebarAgentSessionListId,
    sidebarAgents: agentCatalog.sidebarAgents,
    sidebarAgentsCollapsed: app.sidebarAgentsCollapsed,
    sidebarGroupsCollapsed: app.sidebarGroupsCollapsed,
    sidebarCollapsed: app.sidebarCollapsed,
    sidebarDeleteGroup: app.sidebarDeleteGroup,
    sidebarDeletePopoverStyle: app.sidebarDeletePopoverStyle,
    t: app.t,
    theme: app.theme,
    toggleCollapsedGroupMenu: collapsedGroupMenu.toggleCollapsedGroupMenu,
    toggleDirectSessionListExpanded: conversationNavigation.toggleDirectSessionListExpanded,
    toggleGroupSessionListExpanded: conversationNavigation.toggleGroupSessionListExpanded,
    toggleLocale: app.toggleLocale,
    toggleTheme: app.toggleTheme,
    visibleDirectGroupsFor: conversationNavigation.visibleDirectGroupsFor,
    visibleGroupGroups: conversationNavigation.visibleGroupGroups,
  }

  const systemSettingsController = {
    agentCatalogGroups: agentCatalog.agentCatalogGroups,
    agentDescription: agentCatalog.agentDescription,
    agentImageLabel: agentCatalog.agentImageLabel,
    agentSkillLabel: agentSkills.agentSkillLabel,
    agentState: agentCatalog.agentState,
    cancelInstall: agentManagement.cancelInstall,
    focusedAgentKind: app.focusedAgentKind,
    formError: app.formError,
    installConfirmKind: app.installConfirmKind,
    installedCount: agentCatalog.installedCount,
    installerBusy: agentManagement.installerBusy,
    installerPhaseLabel: agentManagement.installerPhaseLabel,
    installerState: app.installerState,
    isDirectCreationPending: conversationNavigation.isDirectCreationPending,
    knowledgeBaseIcon: knowledgeBase.knowledgeBaseIcon,
    knowledgeBaseLoading: knowledgeBase.knowledgeBaseLoading,
    knowledgeBaseLocationLabel: knowledgeBase.knowledgeBaseLocationLabel,
    knowledgeBasePending: knowledgeBase.knowledgeBasePending,
    knowledgeBasePrimaryActionLabel: knowledgeBase.knowledgeBasePrimaryActionLabel,
    knowledgeBaseStatusLabel: knowledgeBase.knowledgeBaseStatusLabel,
    knowledgeBaseTagItems: knowledgeBase.knowledgeBaseTagItems,
    knowledgeBaseTone: knowledgeBase.knowledgeBaseTone,
    loadKnowledgeBaseStatuses: knowledgeBase.loadKnowledgeBaseStatuses,
    localKnowledgeBaseEntries: knowledgeBase.localKnowledgeBaseEntries,
    openAgentDetail: agentManagement.openAgentDetail,
    openAgentManager: app.openAgentManager,
    openDirect: conversationActions.openDirect,
    openProvider: app.openProvider,
    plannedKnowledgeBaseEntries: knowledgeBase.plannedKnowledgeBaseEntries,
    providerSettings,
    providerSummaryLabel: providerSettings.providerSummaryLabel,
    readyCount: agentCatalog.readyCount,
    readyKnowledgeBaseCount: knowledgeBase.readyKnowledgeBaseCount,
    refreshAgents: agentRefresh.refreshAgents,
    refreshing: app.refreshing,
    requestInstall: agentManagement.requestInstall,
    runKnowledgeBasePrimaryAction: knowledgeBase.runKnowledgeBasePrimaryAction,
    saving: app.saving,
    selectSystemSettingsSection: app.selectSystemSettingsSection,
    supportsExternalProvider: providerSettings.supportsExternalProvider,
    systemSettingsSection: app.systemSettingsSection,
    t: app.t,
  }

  const workspaceModalController = {
    activeGroup: app.activeGroup,
    agentDescription: agentCatalog.agentDescription,
    agentDetailSkillItems: agentSkills.agentDetailSkillItems,
    agentDetailSkillSummary: agentSkills.agentDetailSkillSummary,
    agentDetailSkillsLoading: agentSkills.agentDetailSkillsLoading,
    agentImageLabel: agentCatalog.agentImageLabel,
    agentSoul: agentCatalog.agentSoul,
    agentState: agentCatalog.agentState,
    closeModal: app.closeModal,
    confirmUnlimitedRounds: app.confirmUnlimitedRounds,
    createCustomAgent: agentManagement.createCustomAgent,
    createGroup: conversationActions.createGroup,
    customAgentDeleteArmed: app.customAgentDeleteArmed,
    customAgentForm: agentManagement.customAgentForm,
    deleteArmed: conversationActions.deleteArmed,
    deleteConversation: conversationActions.deleteConversation,
    deleteCustomAgent: agentManagement.deleteCustomAgent,
    dismissDeleteConfirmation: conversationActions.dismissDeleteConfirmation,
    formError: app.formError,
    groupForm: conversationActions.groupForm,
    installerBusy: agentManagement.installerBusy,
    installerState: app.installerState,
    isDirectCreationPending: conversationNavigation.isDirectCreationPending,
    modal: app.modal,
    openDirect: conversationActions.openDirect,
    openProvider: app.openProvider,
    pickGroupDirectory: conversationActions.pickGroupDirectory,
    providerSummaryLabel: providerSettings.providerSummaryLabel,
    readyAgents: agentCatalog.readyAgents,
    requestDeleteConfirmation: conversationActions.requestDeleteConfirmation,
    requestInstall: agentManagement.requestInstall,
    saveGroupSettings: conversationActions.saveGroupSettings,
    saving: app.saving,
    selectedAgentDetail: agentSkills.selectedAgentDetail,
    setAgentSidebarVisibility: agentManagement.setAgentSidebarVisibility,
    settingsForm: conversationActions.settingsForm,
    supportsExternalProvider: providerSettings.supportsExternalProvider,
    t: app.t,
  }

  return { systemSettingsController, workspaceModalController, workspaceSidebarController }
}
